- project:
    check:
      jobs:
        - networking-generic-switch-tempest-dsvm-dlm
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    gate:
      jobs:
        - networking-generic-switch-tempest-dsvm-dlm
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$

